[java_opts]
xms = 64
xmx = 512
metaspacesize = 96
maxmetaspacesize = 256

[jboss]
bindaddress = "0.0.0.0"
bindaddressmanagement = "0.0.0.0"
managementhttpport = 9990
managementhttpsport = 9993
httpport = 8080
httpsport = 8443