image: "ubuntu"
services:
  - docker:dind

stages:
  - test
  - build
  - publish
  - promote

lint:
  stage: test
  script:
    - echo "You should really have some testing for this app..."

create_artifact:
  stage: build
  script:
    - hab pkg build habitat/.

