image: "ubuntu"
services:
  - docker:dind

before_script:
  - apt-get update
  - apt-get install -y curl wget
  - curl https://raw.githubusercontent.com/habitat-sh/habitat/master/components/hab/install.sh | bash
  - hab license accept
  - echo $sig | base64 -d > /hab/cache/keys/jmassardo-20171014002439.pub
  - echo $key | base64 -d > /hab/cache/keys/jmassardo-20171014002439.sig.key
  - export HAB_ORIGIN=jmassardo

stages:
  - test
  - build
  - publish
  - promote

lint:
  stage: test
  script:
    - echo "You should really have some testing for this app..."

create_artifact:
  stage: build
  script:
    - hab pkg build habitat/.

