trigger:
- master

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'Ubuntu 16.04'
    continueOnError: true
    steps:
    - task: vsts-habitat-install@3
    - task: vsts-habitat-signing-key@3
      displayName: 'Signing Origin Key: install'
      inputs:
        habitatOrigin: bldr
    - task: vsts-habitat-build@3
      displayName: 'Build Habitat plan'
      inputs:
        habitatOrigin: bldr
      env:
        HAB_LICENSE: accept-no-persist
    - task: vsts-habitat-expose-habitat-build-vars@3
      displayName: 'Expose Habitat Build Variables'
      inputs:
        habitatSetBuildNumber: true
    - publish: $(System.DefaultWorkingDirectory)/results
      artifact: hart

- stage: DeployToDev
  jobs:
  - deployment: deployment
    pool:
      vmImage: 'Ubuntu 16.04'
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: vsts-habitat-install@3
          - task: vsts-habitat-signing-key@3
            displayName: 'Signing Origin Key: install'
            inputs:
              habitatOrigin: bldr
          - script: |
              source $(Pipeline.Workspace)/hart/last_build.env
              echo "##vso[task.setvariable variable=pkg_artifact]$pkg_artifact"
            displayName: 'Publish Artifact Name'
          - task: vsts-habitat-pkg-upload@3
            displayName: 'Package Upload'
            inputs:
              habitatOrigin: bldr
              habitatPackagePath: '$(Pipeline.Workspace)/hart/$(pkg_artifact)'
              habitatPackageChannel: dev
            env:
              HAB_LICENSE: accept-no-persist

- stage: DeployToStg
  jobs:
  - deployment: deployment
    pool:
      vmImage: 'Ubuntu 16.04'
    environment: 'stg'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: vsts-habitat-install@3
          - task: vsts-habitat-signing-key@3
            displayName: 'Signing Origin Key: install'
            inputs:
              habitatOrigin: bldr
          - script: |
              source $(Pipeline.Workspace)/hart/last_build.env
              /tmp/hab pkg promote $pkg_ident stage
            displayName: 'Promote to Stage'
            env:
              HAB_LICENSE: accept-no-persist

- stage: DeployToProd
  jobs:
  - deployment: deployment
    pool:
      vmImage: 'Ubuntu 16.04'
    environment: 'prod'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: vsts-habitat-install@3
          - task: vsts-habitat-signing-key@3
            displayName: 'Signing Origin Key: install'
            inputs:
              habitatOrigin: bldr
          - script: |
              source $(Pipeline.Workspace)/hart/last_build.env
              /tmp/hab pkg promote $pkg_ident stage
            displayName: 'Promote to Stage'
            env:
              HAB_LICENSE: accept-no-persist